version: '3.8'

services:
  aiogram_bot:
    build: ./aiogram_bot
    container_name: aiogram_bot
    working_dir: /app
    volumes:
      - ./aiogram_bot:/app
    command: ["python", "main.py"]
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - TELEGRAM_USER_ID=${TELEGRAM_USER_ID}
    ports:
      - "64783:64783"
    depends_on:
      - mongo

  bot:
    build:
      context: ./kwork_scrapper
    container_name: kwork_bot
    working_dir: /app
    volumes:
      - ./kwork_scrapper:/app
    command: ["/app/entrypoint.sh"]
    environment:
      - LOGIN=${KWORK_LOGIN}
      - PASSWD=${KWORK_PASSWD}
      - PHONE_LAST=${KWORK_PHONE_LAST}
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWD}@mongo:27017/
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    command: ["--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD}
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWD}
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo_data: